cseg

_dead:
;@dcc.mir inline-simple-store
ld hl,123
ld c,l
ld b,h
ld l,c
ld h,b
push hl
call _sink
pop bc
ret

_live:
;@dcc.mir inline-simple-store
ld hl,456
ld c,l
ld b,h
ld l,c
ld h,b
ld a,c
ret

_fastcall:
;@dcc.mir inline-simple-store
ld hl,789
ld c,l
ld b,h
ld l,c
ld h,b
call __mhf
ret

_conditional:
;@dcc.mir inline-simple-store
ld hl,999
ld c,l
ld b,h
ld l,c
ld h,b
call z,_sink
ld a,c
ret

_sink:
ret
