	ld de,_base+18 ; peep: add_hl_immediate_direct_de
	add hl,de
_combine_adds_preserve_de:
	ld de,-23 ; peep: combine_hl_constant_adds_preserve_de
	add hl,de
	ld de,7
	xor a
	ld a,d
	ret
	ld de,_table+4 ; peep: add_hl_immediate_direct_de
	add hl,de
	ld de,_table+6 ; peep: add_hl_immediate_direct_de
	add hl,de
	ld de,-53 ; peep: combine_hl_constant_adds
	add hl,de
	ld de,7
	add hl,de
	ld a,d
	ld (ix-4),253 ; peep: ix_const_store_hl_dead
	ld (ix-3),255
	ld hl,7
	ld (ix-8),l
	ld (ix-7),h
	push hl
	call _external
	pop bc
	ex de,hl ; peep: push_hl_load_pop_de_to_ex
	ld l,(ix-8)
	ld h,(ix-7)
	add hl,hl
	add hl,de
	ex de,hl ; peep: push_hl_load_pop_de_to_ex
	ld l,(ix-4)
	ld h,(ix-3)
	add hl,de
	ex de,hl ; peep: push_hl_load_pop_de_to_ex
	push iy
	pop hl
	add hl,de
	push hl
	ld l,(hl)
	ld h,(ix-3)
	pop de
	add hl,de
_de_source_near_miss:
	push hl
	ld l,e
	ld h,d
	pop de
	ret
