; static function decline
_ZD:
push ix
ld ix,0
add ix,sp
ld hl,100
ld (ix-2),l
ld (ix-1),h
ld hl,0
ld l,(ix-2)
ld h,(ix-1)
ld a,(hl)
call _external
ld l,(ix-2)
ld h,(ix-1)
ld a,(hl)
call _external
ld l,(ix-2)
ld h,(ix-1)
ld a,(hl)
call _external
ld l,(ix-2)
ld h,(ix-1)
ld a,(hl)
ld a,(ix-2)
add a,1
ld (ix-2),a
jr nc,LDS
inc (ix-1)
LDS:
ld sp,ix
pop ix
ret
; static function accept
_ZA:
push ix
ld ix,0
add ix,sp
ld hl,100
ld (ix-2),l
ld (ix-1),h
ld hl,0
ld l,(ix-2)
ld h,(ix-1)
ld a,(hl)
call __safe
ld l,(ix-2)
ld h,(ix-1)
ld a,(hl)
call __safe
ld e,(ix-2)
ld d,(ix-1)
ex de,hl
ld a,(hl)
ld a,(ix-2)
add a,2
ld (ix-2),a
jr nc,LAS
inc (ix-1)
LAS:
jp LAT
LAT:
or a
ld sp,ix
pop ix
ret
end
