; static function accept
_ZA:
ld l,(ix-2)
ld h,(ix-1)
inc hl
ld (ix-2),l
ld (ix-1),h
ld a,(iy+0)
cp 10
ld hl,0
ld e,(ix-2)
ld d,(ix-1)
ret
; static function a_live
_ZAL:
ld a,7
ld l,(ix-2)
ld h,(ix-1)
inc hl
ld (ix-2),l
ld (ix-1),h
or a
ld e,(ix-2)
ld d,(ix-1)
ret
; static function hl_live
_ZHL:
ld l,(ix-2)
ld h,(ix-1)
inc hl
ld (ix-2),l
ld (ix-1),h
ld a,(hl)
ld e,(ix-2)
ld d,(ix-1)
ret
; static function flags_live
_ZFL:
or a
ld l,(ix-2)
ld h,(ix-1)
inc hl
ld (ix-2),l
ld (ix-1),h
jp z,LF
LF:
ld e,(ix-2)
ld d,(ix-1)
ret
; static function user_asm
_ZU:
; dcc user asm begin
ld l,(ix-2)
ld h,(ix-1)
inc hl
ld (ix-2),l
ld (ix-1),h
; dcc user asm end
ld a,(iy+0)
cp 10
ld hl,0
ld e,(ix-2)
ld d,(ix-1)
ret
end