	cseg

	public _borrow
_borrow:
	push ix
	ld ix,0
	add ix,sp
	dec sp
	dec sp
	ld hl,18
	exx ; peep: ix_spill_exx
	ld hl,9
	exx ; peep: ix_spill_exx
	push hl ; peep: ix_spill_exx
	exx ; peep: ix_spill_exx
	pop de ; peep: ix_spill_exx
	ex de,hl
	ld sp,ix
	pop ix
	ret

	public _stack_live
_stack_live:
	push ix
	ld ix,0
	add ix,sp
	dec sp
	dec sp
	ld hl,21
	ld (ix-2),l
	ld (ix-1),h
	push bc
	nop
	ld e,(ix-2)
	ld d,(ix-1)
	ld sp,ix
	pop ix
	ret
	end
