public _accept
_accept:
push ix
ld ix,0
add ix,sp
ld l,(ix+4)
ld h,(ix+5)
ld e,(ix+6)
ld d,(ix+7)
or a
jp z, L1
ld l,(ix+4)
ld h,(ix+5)
ld e,(ix+6)
ld d,(ix+7)
or a
ld l,(ix+4)
ld h,(ix+5)
ld e,(ix+6)
ld d,(ix+7)
L1:
ld sp,ix
pop ix
ret
public _decline
_decline:
push ix
ld ix,0
add ix,sp
ld l,(ix+4)
ld h,(ix+5)
ld e,(ix+6)
ld d,(ix+7)
call _external
ld l,(ix+4)
ld h,(ix+5)
ld e,(ix+6)
ld d,(ix+7)
ld sp,ix
pop ix
ret
end
