	public _accept
_accept:
	ld l,(ix-4) ; peep: preserve_ix_pointer_compare
	ld h,(ix-3)
	ld e,(ix-2)
	ld d,(ix-1)
	or a
	sbc hl,de
	ret c ; peep: cond_jp_to_cond_ret
	ret z ; peep: cond_jp_to_cond_ret
	ex de,hl
	ld e,(hl)
	inc hl
	ld d,(hl)
	ex de,hl
	or a
	ret
	public _decline
_decline:
	ld l,(ix-2)
	ld h,(ix-1)
	ld e,(ix-4)
	ld d,(ix-3)
	or a
	sbc hl,de
	ret nc ; peep: cond_jp_to_cond_ret
	ld l,(ix-2)
	ld h,(ix-1)
	ld e,(hl)
	inc hl
	ld d,(hl)
	ex de,hl
	ret c ; peep: cond_jp_to_cond_ret
	ret
	end
