	public _accept
_accept:
	ld l,(ix-4) ; peep: preserve_ix_pointer_compare
	ld h,(ix-3)
	ld e,(ix-2)
	ld d,(ix-1)
	or a
	sbc hl,de
	jr c,L1 ; peep: jp_to_jr
	jr z,L1 ; peep: jp_to_jr
	ex de,hl
	ld e,(hl)
	inc hl
	ld d,(hl)
	ex de,hl
	or a
L1:
	ret
	public _decline
_decline:
	ld l,(ix-2)
	ld h,(ix-1)
	ld e,(ix-4)
	ld d,(ix-3)
	or a
	sbc hl,de
	jr nc,L2 ; peep: jp_to_jr
	ld l,(ix-2)
	ld h,(ix-1)
	ld e,(hl)
	inc hl
	ld d,(hl)
	ex de,hl
	jr c,L2 ; peep: jp_to_jr
L2:
	ret
	end
