; six __ldwl candidates save one linked byte
ld e,(hl)
inc hl
ld d,(hl)
ex de,hl
ld e,(hl)
inc hl
ld d,(hl)
ex de,hl
ld e,(hl)
inc hl
ld d,(hl)
ex de,hl
ld e,(hl)
inc hl
ld d,(hl)
ex de,hl
ld e,(hl)
inc hl
ld d,(hl)
ex de,hl
ld e,(hl)
inc hl
ld d,(hl)
ex de,hl
; four __sxde candidates save two linked bytes
ld a,h
rlca
sbc a,a
ld d,a
ld e,a
ld a,h
rlca
sbc a,a
ld d,a
ld e,a
ld a,h
rlca
sbc a,a
ld d,a
ld e,a
ld a,h
rlca
sbc a,a
ld d,a
ld e,a
; six __sxhl candidates save one linked byte
ld a,l
rlca
sbc a,a
ld h,a
ld a,l
rlca
sbc a,a
ld h,a
ld a,l
rlca
sbc a,a
ld h,a
ld a,l
rlca
sbc a,a
ld h,a
ld a,l
rlca
sbc a,a
ld h,a
ld a,l
rlca
sbc a,a
ld h,a
end
